version: "3.8"
services:
  client:
    image: landonconnell/spotify-playlist-generator-client:latest
    container_name: spotify-playlist-generator-client
    environment:
    build:
      context: ./client
    ports:
      - "80:3000"
  server:
    image: landonconnell/spotify-playlist-generator-server:latest
    container_name: spotify-playlist-generator-server
    build:
      context: ./server
    ports:
      - "5000:5000"
