name: Build and Deploy app to Azure

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker images
        run: docker-compose build
      - name: Push images to Docker Hub
        run: |
          docker tag spotify-playlist-generator_client:latest landonconnell/spotify-playlist-generator_client:latest
          docker tag spotify-playlist-generator_server:latest landonconnell/spotify-playlist-generator_server:latest
          docker push landonconnell/spotify-playlist-generator_client:latest
          docker push landonconnell/spotify-playlist-generator_server:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "SPG-WebApp-02"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_eddc24a5c30e4564b0ec076a4e9992ef }}
          images: "index.docker.io/${{ secrets.AzureAppService_ContainerUsername_7fc043ac6f82403da1f1c668945b8afa }}/spotify-playlist-generator_client:${{ github.sha }}"
