name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker images
        run: docker-compose build
      - name: Push images to Docker Hub
        run: |
          docker tag spotify-playlist-generator-client:latest landonconnell/spotify-playlist-generator-client:latest
          docker tag spotify-playlist-generator-server:latest landonconnell/spotify-playlist-generator-server:latest
          docker push landonconnell/spotify-playlist-generator-client:latest
          docker push landonconnell/spotify-playlist-generator-server:latest
